- jwt/algs.go
- jwt/doc.go
- jwt/doc_test.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/keyset.go
- jwt/keyset_test.go
This PR adds an initial implementation of the JWT package, which provides signature verification and claims set validation for [JWTs](https://tools.ietf.org/html/rfc7519) of the [JWS](https://tools.ietf.org/html/rfc7519) form.
The code in this package is similar to that in both the [vault-plugin-auth-jwt](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/path_login.go#L47) and [consul](https://github.com/hashicorp/consul-enterprise/blob/master/internal/go-sso/oidcauth/jwt.go#L24) JWT auth implementations.
I've integrated and tested the code in this PR in the [common-jwt-lib](https://github.com/hashicorp/vault-plugin-auth-jwt/compare/common-jwt-lib) branch of vault-plugin-auth-jwt.
Tests are intentionally absent from this PR in order to first agree on the API and behavior of …
> Adds initial implementation of the JWT package

- oidc/provider_test.go
- oidc/request.go
- oidc/request_test.go
Support for the WithNonce(...) option for NewRequest(..) allows devs to specify their own nonce value.  
This new option is required, if the developer wishes to encode all required Request info into a Request's State.  Encoding all a Request's info into its State would remove the requirement of a Request cache/storage from the developer's application.  We already support a WithState(...) option, and the Request's Nonce was the only Request field which the developer could not specify or change.
> support for the WithNonce(...) oidc.Request option

- oidc/provider.go
- oidc/provider_test.go
- oidc/testing_provider.go
- oidc/testing_provider_test.go
Adding this capability will allow devs to discover and retrieve the provider's published configuration via the well known location of the JSON document.  Using this published configuration, devs can verify that the provider supports the capabilities they need.
> Add Provider.DiscoveryInfo(...) which retrieves the published IdP configuration info

- oidc/testing_provider.go
- oidc/testing_provider_test.go
Added:
* SetExpectedSubject(...) - configuring the expected subject for any JWTs issued by the provider (the default is "alice@example.com")
* ExpectedSubject(...) - returning the configured subject
> TestProvider change: allow devs to control the sub of signed JWTs

- go.mod
- go.sum
This PR resets the version requirement for the `golang.org/x/oauth2` dependency, which was set to a specific version in PR  https://github.com/hashicorp/cap/pull/14. I missed seeing that this was changed when reviewing PR https://github.com/hashicorp/cap/pull/25. See PR https://github.com/hashicorp/cap/pull/14 for more context on why we're setting this specific version. 
An alternative would be to fix the etcd/grpc incompatibility in Vault based on guidance from https://github.com/etcd-io/etcd/issues/12124.
- https://github.com/hashicorp/vault-plugin-auth-azure/pull/43
> Set specific version of golang.org/x/oauth2

- oidc/testing_provider.go
While working on the Boundary TF provider this log line kept bothering me:
```
2021-06-13T07:37:08.771Z [INFO]  dev-oidc: cleanup of cached codes shutting down: EXTRA_VALUE_AT_END=<nil>
```
> Remove erroneous nil

- util/util.go
Working within containers as an interactive developer environment (devcontainer) is becoming more prevalent, but improper WSL detection when using OIDC based authentication methods with Vault and Boundary makes using these command line tools problematic in such an environment.
The current method for detecting WSL is to examine /proc/version, looking for the presence of the string "microsoft". However, since Microsoft also uses their linux kernels as the basis of their published devcontainer images/layers, this causes the isWSL() function to return true within that environment as well. When openURL() is subsequently called in order to launch a browser and complete authentication, vault and boundary will opt to try and launch cmd.exe, thinking the environment is WSL, which then fails.
This …
> adjust WSL detection

- CHANGELOG.md
- ldap/client.go
- ldap/client_exported_test.go
- ldap/options.go
The new WithUserAttributes option allows callers to request the attributes be returned for the authenticating user.
> feature (ldap): add WithUserAttributes option

- .github/workflows/go.yml
- ldap/client_test.go
Previously, no build/test failures would result in a non-zero exit status. This PR should now fail the build/tests steps whenever an error is encountered.
Here's an example of the issue:
https://github.com/hashicorp/cap/actions/runs/3989282340/jobs/6841516383#step:6:10
Other fixes/updates:
- enable verbose testing. (open to dropping this, if it is not desired)
- fix panic in `TestClient_connect`
- bump the min go version to 1.19
- drop support for dep
> CI: ensure that all build/test failures are properly detected

- go.mod
- go.sum
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/keyset.go
- oidc/id_token.go
- oidc/testing.go
- oidc/testing_provider.go
The square/go-jose project is deprecated, and is set to be archived on Feb. 27th, 2023. Luckily the project has been moved to go-jose/go-jose.
ref: https://github.com/square/go-jose#go-jose-v1v2-deprecated
> Replace square/go-jose with go-jose/go-jose/v3

- CHANGELOG.md
- oidc/provider.go
- oidc/request.go
This PR fixes an integer overflow that occurred within `auth_time` claim validation when compiled for 32bit. This was surfaced in Vault's [32bit tests](https://github.com/hashicorp/vault-enterprise/actions/runs/5179545255/jobs/9332600305#step:10:869) where we use `cap/oidc` as a client to Vault's OIDC provider (see [oidc_provider_test.go#L272](https://github.com/hashicorp/vault/blob/main/vault/external_tests/identity/oidc_provider_test.go#L272))
The overflow occurred by directly negating the [`maxAge.seconds`](https://github.com/hashicorp/cap/blob/main/oidc/request.go#L425) which is a `uint`. This caused the `opts.withMaxAge.authAfter` duration to be way in the future. I added additional error logs in the Vault tests to show the value of the duration before and after changes in this PR. …
> Fixes overflow in auth_time claim validation on 32bit

- CHANGELOG.md
- ldap/client.go
- ldap/client_test.go
- ldap/config.go
- ldap/conn_test.go
- [fix (ldap): properly escape user filters with UPN domains](https://github.com/hashicorp/cap/commit/1d638ddf393c33b674f2b4f9b249a7013cab604b)
- [fix (ldap): increase max tls to 1.3](https://github.com/hashicorp/cap/commit/822334cca7e6209d4ed206cb36f528da2e9926cb)
- [fix (ldap): improve EscapeValue(...)](https://github.com/hashicorp/cap/commit/dadacf7ea25e01ca7e52f07d3c444bd562d513d9)
- [fix (ldap): use text template for rendering filters](https://github.com/hashicorp/cap/commit/f30bbc56e5cea51d581987bcfc37a5af3d982b3a)
> Address a set of LDAP issues.

- saml/authn_request.go
- saml/authn_request_test.go
- saml/config.go
- saml/config_test.go
- saml/demo/main.go
- saml/error.go
- saml/internal/test/context.go
- saml/models/metadata/common.go
- saml/models/metadata/entity_descriptor.go
- saml/models/metadata/idp_sso_descriptor.go
- saml/models/metadata/sp_sso_descriptor.go
- saml/response.go
- saml/sp.go
- saml/sp_test.go
This PR adds the ability to specify identity provider metadata as either an XML document or individual parameters. This is a common way that identity providers offer metadata to configure SAML service providers. I've introduced them as functional options to the `Config` struct.
Additionally, I've changed the `Config` struct to take in strings instead of `url.URL` for URL parameters. This felt more user friendly and aligns with my general experience using libraries that take in URLs (including `cap/oidc` and `cap/jwt`). I'm happy to change this back if there is disagreement.
I've manually tested both XML identity provider metadata and individual parameters using Okta and the demo program. If everything looks reasonable, I'll add testing to this PR.
> Adds ability to provide IdP metadata as XML or individual parameters

- saml/authn_request.go
- saml/authn_request_test.go
- saml/config.go
- saml/models/core/request.go
- saml/test/provider.go
This PR adds tests for the `provider.AuthnRequestRedirect` function. Additionally, it adds more docs to exported functions.
> Add  tests for `AuthnRequestRedirect`

- CHANGELOG.md
- ldap/client.go
We've added worker pool to make looking up token groups more performant.  token groups have to be looked up individually, so if a user is a member of MANY groups it can be helpful to do these lookups concurrently vs serially. This is based on benchmarks and a subsequent implementation within vault's codebase for looking up token groups. 
See: https://github.com/hashicorp/vault/pull/22659
> feat (ldap): add worker pool for LDAP token group lookups

- saml/models/core/response.go
- saml/models/core/response_test.go
- saml/response.go
This PR adds a few helper methods for the SAML response. They allow for obtaining the assertions, attributes, and subject name ID. These helpers cover our usage of the response in the Vault SAML auth method and were useful to clean up additional nil checking that was previously required.
I will add tests before merging if this looks reasonable. I also want to restructure the tests in `response_test.go`.
> saml: adds helpers for response assertions, subject, issuer, and attributes

- .github/workflows/fuzz.yml
The action is now pinned according to tsccr, so thats what we should also now reflect in the comment.
> adjusted comment in action

- saml/go.mod
1.19 is EOL, so updating to 1.20 -> we probably don't want to require 1.21 yet since it would no longer become a "recommendation" but rather a requirement.
> chore: update go version to a supported version

- saml/authn_request.go
This PR truncates the `IssueInstant` of the SAML `AuthNRequest` to microseconds. This enables our service provider to be compatible with SAML enterprise applications in Microsoft Entra (formerly Azure AD). I was able to reproduce the failure to parse the `IssueInstant` and verify this change fixes it in Vault.
This is needed because the `AuthnRequest` processing expects the `IssueInstant` to have the [round-trip format ("o")](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#Roundtrip) which has a max of 10^-7 second precision. Go `time.Now()` has [varying precision](https://github.com/golang/go/issues/41087) depending on which OS it's running on. On linux, the precision is 10^-9 (nanoseconds) which caused the parsing failure. Truncating to …
> saml: truncate issue instant to microseconds

- jwt/jwt.go
- jwt/jwt_test.go
This PR is intended as a building block to add support for multiple JWKS URLs in a single auth method. 
Main changes:
* Update the `Validator` to take multiple key sets.
* Update the validation logic to loop over keysets and attempt to verify JWT with any available
> Add support for multiple JWKS urls

- saml/response_test.go
- saml/test/provider.go
This PR adds the ability to the SAML test provider to create signed SAML responses. It uses the [goxmldsig](https://github.com/russellhaering/goxmldsig) library for this purpose, which is also used by the underlaying `gosaml2` library used in `cap/saml`.  
Before, this library used `samltest.id` (a test SAML Identity provider), which doesn't exist anymore. The tests for parsing SAML responses have been updated to use the test provider.
I'll open a follow up PR to improve the test SAML identity provider in `cap/saml`. Areas to improve:
- Provide more options to modify the SAML response, such that we can get rid of any hard coded SAML response XML strings.
- Create the IDP Metadata programatically with options.
> Add ability to the SAML test provider to create signed SAML responses

- oidc/config.go
- oidc/config_test.go
- oidc/docs_test.go
- oidc/provider.go
- oidc/provider_test.go
Add support for specifying an optional http.RoundTripper for a provider config.  If specified the http client will use the RoundTripper when making requests to the provider.
> feat (config): add support for a http.RoundTripper

- CHANGELOG.md
- oidc/pkce_verifier.go
- oidc/pkce_verifier_test.go
This commit adds the WithVerifier option to the
oidc package. This option allows the user to
specify a custom verifier for the PKCE code
challenge.
> feat (oidc): add WithVerifier

- ldap/client.go
- ldap/client_exported_test.go
- ldap/client_test.go
This PR adds a check in the `ldap` package's `getUserDN` function that ensures the number of entries returned from the user DN LDAP search is one (in the same way we already handle multiple users in [`getUserBindDN`](https://github.com/hashicorp/cap/blob/5c3419e3e8ad01a7bc051f155964ab537a78cfec/ldap/client.go#L695-L698)). This should prevent authentication attacks that can leverage the fact that we currently return the last user DN if there are duplicate users.
The bulk of the changes are unit tests additions at the `getUserBindDN` and `getUserDN` level, which include test cases ensuring we error when there are multiple users returned.
Ticket: [VAULT-27421](https://hashicorp.atlassian.net/browse/VAULT-27421)
[VAULT-27421]: https://hashicorp.atlassian.net/browse/VAULT-27421?atlOrigin=eyJpIj …
> ldap getUserDN handle multiple users
